import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ResizableNavbar from "@/components/ui/resizable-navbar";
import Lamp from "@/components/ui/lamp"; // 👈 IMPORT CORRECTO

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Luxe Style",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* 👇 LAMP DE FONDO GLOBAL */}
        <Lamp />

        {/* ⭐ NAVBAR GLOBAL */}
        <ResizableNavbar />

        {/* ⭐ CONTENIDO DE LA PÁGINA */}
        {children}

      </body>
    </html>
  );
}
