import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs"; 

import ResizableNavbar from "../components/ui/resizable-navbar";
import Navbar from "@/components/layout/Navbar";



const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Luxe Style",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>   {/* ⭐ ENVUELVE TODA LA APP CON CLERK */}
      <html lang="es">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

          {/* ⭐ LAMP GLOBAL */}
            

          {/* ⭐ NAVBAR GLOBAL */}
          <ResizableNavbar />

          {/* ⭐ CONTENIDO DE CADA PÁGINA */}
          {children}

        </body>
      </html>
    </ClerkProvider>
  );
}
